#include "mapSketch.h"

extern std::vector<std::string> mMapSketch = {
		"                            ",
		"                            ",
		"                            ",
		"############################",
		"#cccccccccccc##cccccccccccc#",
		"#c####c#####c##c#####c####c#",
		"#e#  #c#   #c##c#   #c#  #e#",
		"#c####c#####c##c#####c####c#",
		"#cccccccccccccccccccccccccc#",
		"#c####c##c########c##c####c#",
		"#c####c##c########c##c####c#",
		"#cccccc##cccc##cccc##cccccc#",
		"######c##### ## #####c######",
		"     #c##### ## #####c#     ",
		"     #c##          ##c#     ",
		"     #c## ###@@@## ##c#     ",
		"######c## #      # ##c######",
		"      c   #      #   c      ",
		"######c## #      # ##c######",
		"     #c## ######## ##c#     ",
		"     #c##          ##c#     ",
		"     #c## ######## ##c#     ",
		"######c## ######## ##c######",
		"#cccccccccccc##cccccccccccc#",
		"#c####c#####c##c#####c####c#",
		"#c####c#####c##c#####c####c#",
		"#ecc##ccccccc  ccccccc##cce#",
		"###c##c##c########c##c##c###",
		"###c##c##c########c##c##c###",
		"#cccccc##cccc##cccc##cccccc#",
		"#c##########c##c##########c#",
		"#c##########c##c##########c#",
		"#cccccccccccccccccccccccccc#",
		"############################",
		"                            ",
		"                            ",
};